### ISSUE TITLE
[WAGON-412] Error injecting constructor, java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#474]
**[David Ireland](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david@lshift.net)** opened **[WAGON-412](https://issues.apache.org/jira/browse/WAGON-412?redirect=false)** and commented

When I try to deploy using the wagon, it fails to initialise with the attached error.

---

**Affects:** 2.6

**Attachments:**
- [webdav-error.log](https://issues.apache.org/jira/secure/attachment/12720728/webdav-error.log) (_7.35 kB_)

**Issue Links:**
- [WAGON-409](https://issues.apache.org/jira/browse/WAGON-409) Wagon-webdav-jackrabbit throws Class Not Found Exception.
 (_**"duplicates"**_)

2 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Rene Krell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rkrell)** commented

Got the same problem during a build on Jenkins 1.532.2 using Maven 3.2.1.
Defined extension in POM:

```xml
<extension>
   <groupId>org.apache.maven.wagon</groupId>
   <artifactId>wagon-webdav-jackrabbit</artifactId>
   <version>2.5</version>
 </extension>
```

**Comment by jira-importer** [comment]
**[Denis Kostousov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=denis.kostousov@gmail.com)** commented

Same problem on 2.6 with maven 3.2.1, 3.1.1, 3.0.5
Works fine on 2.4
